/**
 * 
 */
package dsalgoproblems.project.euler;

/**
 * @author shekh
 * 
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 *
 */
public class EvenFibonacciNumbers {

	public static void main(String[] args) {
		int fib0 = 1;
		int fib1 = 2;
		int fib2 = -1;
		int sum = fib1;
		
		while(fib2 <= 4000000){
			fib2 = fib0+fib1;
			if(fib2 % 2 == 0){
				sum = sum + fib2;
			}
			fib0 = fib1;
			fib1 = fib2;
		}
		System.out.println(fib2);
	}
}